USE `DATASIRPI_CONTACTS`;

CREATE TABLE IF NOT EXISTS `CONTACTS` (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    MOBILE varchar(20) NOT NUll,
    EMAIL varchar(100) NUll,
    DELETED varchar(1) NOT NUll,
    CREATED_ON DATETIME NOT NUll,
    CREATED_BY varchar(50) NOT NUll,
    MODIFIED_ON DATETIME NOT NUll,
    MODIFIED_BY varchar(50) NOT NUll
);